### ISSUE TITLE
Team Goal: Talk to DigitalGov University about supporting their content

### ISSUE THREAD

**Issue by awfrancisco** [18F/edu#11]
### Detailed information

DigitalGov University has hundreds of webinars and instructional videos, but few supporting documents. 18F EDU would like to coordinate our work so we can provide additional online trainings to pair with their videos. This step is aimed at determining the best places to overlap and what DGU sees as the needs of their users. 
### Tasks to completion
- [ ] Pick 1 or 2 EDU people to work with DGU team
- [ ] Set up meeting with DGU team to determine good overlap
- [ ] Create plan for pilot overlap between DGU webinar and EDU materials.

**Comment by awfrancisco** [comment]
_Top Attended Webinars_
1.  [Plain Language: Writing for the Web](http://www.digitalgov.gov/event/plain-language-writing-for-the-web-2/) _(Oct. 2014) - 616 attendees_
2.  [How Government Can Prepare for and Respond to Social Media Hacks](https://www.digitalgov.gov/event/how-government-can-prepare-for-and-respond-to-social-media-hacks/) (Jan 2015) - 338 attendees
3.  [Introducing to the U.S. Web Design Standards](http://www.digitalgov.gov/event/u-s-web-design-standards/) (Oct. 2015) - 305 attendees
4.  [Essentials of Animated Gifs for Government](http://www.digitalgov.gov/event/essentials-of-animated-gifs-for-government/) (April 2015) - 223 attendees
5.  [Moving to Structured Content: It Works Smarter, Travel Further](http://www.digitalgov.gov/event/moving-to-structured-content-it-works-smarter-travels-further/) (Oct. 2015) - 196 attendees
6.  [Creating Infographics](http://www.digitalgov.gov/event/infographics-stories-from-an-in-house-gov-design-team/) (Nov. 2015) - 181 attendees
7.  [User Research and The Paperwork Reduction Act: How to Get it Done](http://www.digitalgov.gov/event/user-research-and-the-paperwork-reduction-act/) (Jan 2015) - 169 attendees
8.  [Where to Start with Structured Data and Content ](http://www.digitalgov.gov/event/where-to-start-with-structured-data-and-content/)(March 2015) - 166 attendees
9.  [After You Hit Send: Using Analytics to Showcase Success](http://www.digitalgov.gov/event/after-you-hit-send-using-analytics-to-showcase-success/) (Jan 2015) - 165 attendees
10. [How to Run an Agile Project in Government](http://www.digitalgov.gov/event/how-to-run-an-agile-project-in-government/) (Dec. 2014) - 159 attendees
11. [An Introduction to HTTPS](http://www.digitalgov.gov/event/intro-to-https/) (July 2015) - 144 attendees

_Highest Rated Webinars_ (highest % of survey responses & highest
overall experience)
1.  [An Introduction to HTTPS ](http://www.digitalgov.gov/event/intro-to-https/)
2.  [Essentials of Animated Gifs for Government](http://www.digitalgov.gov/event/essentials-of-animated-gifs-for-government/)
3.  [Customer Experience Case Study: CDC’s Clear Communication Index](http://www.digitalgov.gov/event/customer-experience-case-study-cdc-clear-communication-index/)
4.  [How to Run an Agile Project in Government ](http://www.digitalgov.gov/event/how-to-run-an-agile-project-in-government/)
5.  [Plain Language: Writing for the Web](http://www.digitalgov.gov/event/plain-language-writing-for-the-web-2/)
6.  [The State of Federal Customer Experience – How to Improve and the Benefits](http://www.digitalgov.gov/event/the-state-of-federal-customer-experience-how-to-improve-and-the-benefits/)
7.  [Introducing the U.S. Web Design Standards](http://www.digitalgov.gov/event/u-s-web-design-standards/)
8.  [Adopting Agile](http://www.digitalgov.gov/event/adopting-agile/)
9.  [Using Mobile User Experience Guidelines to Create Stellar Mobile Products](http://www.digitalgov.gov/event/using-mobile-user-experince-guidelines-to-create-stellar-mobile-products/)
10. [Design Secrets of The World's Best E-government Websites](http://www.digitalgov.gov/event/design-secrets-of-the-worlds-best-e-government-websites/)
