### ISSUE TITLE
Team Goal: Connect with Kara about Media Training and Speaker Camp

### ISSUE THREAD

**Issue by awfrancisco** [18F/edu#16]
And follows with more detailed information:
- To better coordinate across 18F trainings, we should set up a meeting with Kara, so we can loop her trainings into the 18F EDU umbrella. 
### Detailed information

Kara is doing a great job on her trainings, but since they are education opportunities for 18F they should probably be somewhat under the 18F EDU umbrella, even if Kara is still managing them. Probably don't need to change much now, but good for future connections/alignments. 
### Tasks to completion
- [ ] Pre-brainstorm how we'd like to connect
- [ ] Set up meeting with Kara
- [ ] Report back to 18F Edu on the meeting and next steps

**Comment by kategarklavs** [comment]
@awfrancisco I'd love to join this conversation! Let me know when you meet with Kara?

**Comment by mbland** [comment]
"Speakers' Bureau" starting up which may cover this. Won't take over Speaker Camp, but may serve as a hub for speaking issues in general. @awfrancisco can offer more details.
