### ISSUE TITLE
Team goal: Determine how to interact with onboarding process and materials

### ISSUE THREAD

**Issue by mbland** [18F/edu#7]
### Link to document
- Google Doc (TBD)
### Detailed information

To help maintain our new-and-improved onboarding process and materials, we would like to explore and to clarify how Edu can help maintain and extend the onboarding work once the current sprint winds down. Mel and Andrew are scheduled to complete this sprint by Thanksgiving.
### Audience

Check all that apply:
- [ ] General
- [ ] Trade specific
- [ ] All levels
- [ ] Beginner
- [ ] Intermediate
- [ ] Advanced
### Tasks to completion
- [x] Talk to Mel and Andrew
- [ ] Find out if there are already plans for a permanent onboarding team
- [ ] Get an overview/inventory of the existing courses and materials and familiarize ourselves

**Comment by awfrancisco** [comment]
@mbland, @gboone and I talked to Melody. There will likely be a person who is tasked with managing the onboarding process, and we will work with them to manage the training content and make any updates as needed. So EDU for content management, new person for people/process management.
